server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost
    password: 123456
  mail:
    host: smtp.163.com
    port: 465
    username: a15298219120@163.com
    password: DPFPAAJBRPAIYIGL
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  thymeleaf:
    cache: false

logging:
  level:
    com.tmy: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.tmy.*.entity

